# Project: Lq
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = p1157.o Luogu/p1036.o
LINKOBJ  = p1157.o Luogu/p1036.o
LIBS     = -L"D:/Users/LWZ/Dev-Cpp/MinGW64/lib" -L"D:/Users/LWZ/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -pg -g3
INCS     = -I"D:/Users/LWZ/Dev-Cpp/MinGW64/include" -I"D:/Users/LWZ/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Users/LWZ/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Users/LWZ/Dev-Cpp/MinGW64/include" -I"D:/Users/LWZ/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Users/LWZ/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Users/LWZ/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Lq.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11 -pg -g3
CFLAGS   = $(INCS) -std=gnu++11 -pg -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Luogu/p1036.o: Luogu/p1036.cc
	$(CPP) -c Luogu/p1036.cc -o Luogu/p1036.o $(CXXFLAGS)
